# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/afex/hystrix-go"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[override]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[override]]
  name = "github.com/nlopes/slack"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/micro/cli"

[[constraint]]
  branch = "master"
  name = "github.com/micro/go-api"

[[constraint]]
  name = "github.com/micro/go-micro"
  version = "0.15.1"

[[constraint]]
  name = "github.com/micro/micro"
  version = "0.17.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[prune]
  go-tests = true
  unused-packages = true
